### ISSUE TITLE
Provide an RSS/Atom Feed

### ISSUE THREAD

**Issue by Kaligule** [vereis/blog#24]
I like your blog a lot and would like to subscribe to it via a Webfeed. It would be great if there was one.

**Comment by vereis** [comment]
That's a great idea.

It's been something I wanted to implement for awhile but never got around to it 😊 I'll take a look at adding support real soon!

Thanks for the support ❤️

**Comment by vereis** [comment]
Hey @Kaligule I've implemented a basic RSS feed which you can find [here](https://cbailey.co.uk/rss) and it's also linked here: 
![image](https://user-images.githubusercontent.com/15597865/114310813-10cca480-9ae4-11eb-9ba2-8f9557429213.png)

Let me know if there are any issues, if not I'll close this issue 😊

**Comment by Kaligule** [comment]
Looks great. Now all there is to do is wait for a new post so we can see if updating works. Thanks a lot.
